"""Prepare THGNN training samples from processed market data and relations."""
from __future__ import annotations

import argparse
import pickle
from pathlib import Path

import networkx as nx
import numpy as np
import pandas as pd
import torch
from torch.autograd import Variable
from tqdm import tqdm

FEATURE_COLUMNS = ["open", "high", "low", "close", "to", "vol"]


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--data-path",
        type=Path,
        default=Path("data") / "nifty50.pkl",
        help="Path to the processed market data pickle file.",
    )
    parser.add_argument(
        "--relation-dir",
        type=Path,
        default=Path("data") / "relation",
        help="Directory containing relation matrices (generated by generate_relation.py).",
    )
    parser.add_argument(
        "--output-dir",
        type=Path,
        default=Path("data") / "data_train_predict",
        help="Directory where graph samples will be stored.",
    )
    parser.add_argument(
        "--daily-stock-dir",
        type=Path,
        default=Path("data") / "daily_stock",
        help="Directory where daily stock metadata will be stored.",
    )
    parser.add_argument(
        "--window",
        type=int,
        default=20,
        help="Number of previous trading days used to build each graph sample.",
    )
    parser.add_argument(
        "--horizon",
        type=int,
        default=3,
        help="Number of future trading days to forecast for each sample.",
    )
    parser.add_argument(
        "--pos-threshold",
        type=float,
        default=0.1,
        help="Threshold for positive edges when building the adjacency matrix.",
    )
    parser.add_argument(
        "--neg-threshold",
        type=float,
        default=0.1,
        help="Threshold for negative edges when building the adjacency matrix.",
    )
    parser.add_argument(
        "--start-date",
        type=str,
        default=None,
        help="Optional lower bound (inclusive) on relation file dates (YYYY-MM-DD).",
    )
    parser.add_argument(
        "--end-date",
        type=str,
        default=None,
        help="Optional upper bound (inclusive) on relation file dates (YYYY-MM-DD).",
    )
    return parser.parse_args()


def load_market_data(path: Path) -> pd.DataFrame:
    with path.open("rb") as fh:
        df = pickle.load(fh)
    df = pd.DataFrame(df)
    df["dt"] = pd.to_datetime(df["dt"])
    return df.sort_values(["dt", "code"]).reset_index(drop=True)


def trading_days(df: pd.DataFrame) -> list[pd.Timestamp]:
    return df["dt"].drop_duplicates().sort_values().tolist()


def build_adj_matrices(
    adj_all: pd.DataFrame,
    pos_threshold: float,
    neg_threshold: float,
) -> tuple[torch.Tensor, torch.Tensor]:
    pos_graph = nx.Graph(adj_all > pos_threshold)
    pos_adj = nx.adjacency_matrix(pos_graph).toarray()
    pos_adj = pos_adj - np.diag(np.diag(pos_adj))
    pos_adj_tensor = torch.from_numpy(pos_adj).type(torch.float32)

    neg_graph = nx.Graph(adj_all < -neg_threshold)
    neg_adj = nx.adjacency_matrix(neg_graph)
    neg_adj.data = np.ones(neg_adj.data.shape)
    neg_adj = neg_adj.toarray()
    neg_adj = neg_adj - np.diag(np.diag(neg_adj))
    neg_adj_tensor = torch.from_numpy(neg_adj).type(torch.float32)
    return pos_adj_tensor, neg_adj_tensor


def main() -> None:
    args = parse_args()
    if args.horizon < 1:
        raise ValueError("--horizon must be a positive integer")

    df = load_market_data(args.data_path)
    dates = trading_days(df)

    relation_dir = args.relation_dir
    output_dir = args.output_dir
    daily_stock_dir = args.daily_stock_dir
    output_dir.mkdir(parents=True, exist_ok=True)
    daily_stock_dir.mkdir(parents=True, exist_ok=True)

    start_filter = pd.to_datetime(args.start_date) if args.start_date else None
    end_filter = pd.to_datetime(args.end_date) if args.end_date else None

    relation_files = sorted(path for path in relation_dir.glob("*.csv"))
    if start_filter:
        relation_files = [p for p in relation_files if pd.to_datetime(p.stem) >= start_filter]
    if end_filter:
        relation_files = [p for p in relation_files if pd.to_datetime(p.stem) <= end_filter]

    if not relation_files:
        raise RuntimeError("No relation files found. Please run generate_relation.py first.")

    relation_map = {pd.to_datetime(path.stem): path for path in relation_files}
    valid_days = [d for d in dates if d in relation_map]
    if start_filter:
        valid_days = [d for d in valid_days if d >= start_filter]
    if end_filter:
        valid_days = [d for d in valid_days if d <= end_filter]

    for end_data in tqdm(valid_days):
        relation_path = relation_map[end_data]
        adj_all = pd.read_csv(relation_path, index_col=0)
        if adj_all.empty:
            print(f"Skipping {relation_path.name} - empty relation matrix.")
            continue
        adj_stock_set = list(adj_all.index)
        pos_adj, neg_adj = build_adj_matrices(adj_all, args.pos_threshold, args.neg_threshold)

        end_index = dates.index(end_data)
        if end_index < args.window - 1:
            continue
        start_data = dates[end_index - (args.window - 1)]
        df_window = df[(df["dt"] >= start_data) & (df["dt"] <= end_data)]

        feature_all = []
        labels = []
        day_last_code = []
        for code in adj_stock_set:
            df_stock = df_window[df_window["code"] == code]
            values = df_stock[FEATURE_COLUMNS].values
            if values.T.shape[1] != args.window:
                continue
            df_stock_full = df[df["code"] == code].reset_index(drop=True)
            current_rows = df_stock_full.index[df_stock_full["dt"] == end_data].tolist()
            if not current_rows:
                continue
            start_idx = current_rows[0]
            end_idx = start_idx + args.horizon
            if end_idx > len(df_stock_full):
                continue
            future_window = df_stock_full.iloc[start_idx:end_idx]
            future_labels = future_window["label"].values
            if len(future_labels) != args.horizon:
                continue
            if np.isnan(future_labels).any():
                continue
            feature_all.append(values)
            labels.append(future_labels.astype(np.float32))
            day_last_code.append([code, end_data.strftime("%Y-%m-%d")])

        if not feature_all:
            continue

        if len(feature_all) != len(adj_stock_set):
            # Skip samples that cannot represent the entire relation graph.
            continue

        features = torch.from_numpy(np.array(feature_all)).type(torch.float32)
        label_tensor = torch.tensor(np.array(labels), dtype=torch.float32)
        mask = [True] * len(labels)

        result = {
            "pos_adj": Variable(pos_adj),
            "neg_adj": Variable(neg_adj),
            "features": Variable(features),
            "labels": Variable(label_tensor),
            "mask": mask,
        }

        graph_output = output_dir / f"{end_data.strftime('%Y-%m-%d')}.pkl"
        with graph_output.open("wb") as fh:
            pickle.dump(result, fh)

        daily_df = pd.DataFrame(columns=["code", "dt"], data=day_last_code)
        daily_output = daily_stock_dir / f"{end_data.strftime('%Y-%m-%d')}.csv"
        daily_df.to_csv(daily_output, header=True, index=False, encoding="utf_8_sig")


if __name__ == "__main__":
    main()
